USE [MIS_GRUPO_02]
GO

DROP TABLE BT_PASAJES
DROP TABLE BT_DESPACHOS
DROP TABLE LK_ESTACION
DROP TABLE LK_LINEA
DROP TABLE LK_TREN
DROP TABLE LK_RANGO
DROP TABLE LK_PERSONA
DROP TABLE LK_TIEMPO
DROP TABLE LK_CAUSA