USE [MIS_GRUPO_02]
GO

/***** CREAR TABLAS *****/

-- Tabla LK Línea
CREATE TABLE LK_LINEA(
	SK_LINEA bigint PRIMARY KEY IDENTITY(1,1) NOT NULL,
	DESC_LINEA nvarchar(255) NOT NULL
	)
GO

-- Tabla LK Estación
CREATE TABLE LK_ESTACION(
	SK_ESTACION bigint PRIMARY KEY IDENTITY(1,1) NOT NULL,
	ID_ESTACION bigint UNIQUE NOT NULL,
	DESC_ESTACION nvarchar(255) NOT NULL,
	SK_LINEA bigint REFERENCES LK_LINEA(SK_LINEA),
	DESC_LINEA nvarchar(255) NOT NULL,
	COD_BARRIO int NOT NULL,
	DESC_BARRIO nvarchar(255) NOT NULL,
	ASCENSOR int NOT NULL,
	ESCALERA int NOT NULL,
	ADAPTADO bit NOT NULL,
	ACCESIBLE bit NOT NULL,
	POS_X float NOT NULL,
	POS_Y float NOT NULL 
  )
GO
-- Tabla LK Tren
CREATE TABLE LK_TREN(
	SK_TREN bigint PRIMARY KEY IDENTITY(1,1) NOT NULL,
	TREN_ID int NOT NULL,
	CAPACIDAD int DEFAULT 0 NOT NULL
	)
GO

-- Tabla LK_RANGO
CREATE TABLE LK_RANGO(
	SK_RANGO bigint PRIMARY KEY IDENTITY(1,1) NOT NULL,
	HORA_INICIO time NOT NULL,
	HORA_FIN time NOT NULL
	)
GO

-- Tabla LK_PERSONA
CREATE TABLE LK_PERSONA(
	SK_PERSONA bigint PRIMARY KEY IDENTITY(1,1) NOT NULL,
	CONDICION_SOCIAL nvarchar(255) NOT NULL
	)
GO

-- Tabla LK_TIEMPO
CREATE TABLE LK_TIEMPO(
	SK_TIEMPO bigint PRIMARY KEY IDENTITY(1,1) NOT NULL,
	AÑO int NOT NULL,
	MES int NOT NULL,
	DIA_SEMANA int NOT NULL,
	DIA int NOT NULL
	)
GO

-- Tabla LK_CAUSA
CREATE TABLE LK_CAUSA(
	SK_CAUSA bigint PRIMARY KEY IDENTITY(1,1) NOT NULL,
	DESCRIPCION varchar(255) NOT NULL,
	ID_CAUSA varchar(255) NOT NULL
	)
GO

-- Tabla BT_PASAJES
CREATE TABLE BT_PASAJES(
	FK_RANGO bigint REFERENCES LK_RANGO(SK_RANGO),
	FK_TIEMPO bigint REFERENCES LK_TIEMPO(SK_TIEMPO),
	FK_ESTACION bigint REFERENCES LK_ESTACION(SK_ESTACION),
	FK_PERSONA bigint REFERENCES LK_PERSONA(SK_PERSONA),
	PAX_TOTAL bigint NOT NULL,
	CONSTRAINT PK_PASAJES PRIMARY KEY CLUSTERED(FK_RANGO , FK_TIEMPO, FK_ESTACION, FK_PERSONA)
	)
GO

-- Tabla BT_DESPACHOS
CREATE TABLE BT_DESPACHOS(
	FK_LINEA bigint REFERENCES LK_LINEA(SK_LINEA),
	FK_TREN bigint REFERENCES LK_TREN(SK_TREN),
	FK_CAUSA bigint REFERENCES LK_CAUSA(SK_CAUSA),
	FK_TIEMPO bigint REFERENCES LK_TIEMPO(SK_TIEMPO),
	FK_RANGO bigint REFERENCES LK_RANGO(SK_RANGO),
	DESPACHOS bigint NOT NULL,
	VAGONES bigint NOT NULL,
	KILOMETROS float NOT NULL,
	COMERCIAL bit NOT NULL,
	CONSTRAINT PK_DESPACHOS PRIMARY KEY CLUSTERED(FK_LINEA , FK_TREN, FK_CAUSA, FK_TIEMPO, FK_RANGO)
	)
GO
